#!/bin/bash

I=1
M=$(xrandr --query | grep " connected" | wc -l)
if [[ "$M" == 1 ]]; then
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor $(bspc query -M | awk NR==2) -r
elif [[ "$M" == 2 ]]; then
    bspc monitor $(bspc query -M | awk NR==1) -d 1 2
    bspc monitor $(bspc query -M | awk NR==2) -d 3 4 5 6 7 8 9 10
elif [[ "$M" == 3 ]]; then
    bspc monitor $(bspc query -M | awk NR==1) -d 1 2 3 6 7 8 9 10
    bspc monitor $(bspc query -M | awk NR==2) -d 4
    bspc monitor $(bspc query -M | awk NR==3) -d 5
else
for monitor in $(bspc query -M); do
bspc monitor $monitor \
    -n "$I" \
    -d $I/{a,b,c}
    let I++
    done
fi
