#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Init compton
compton --config $HOME/.config/compton/compton.conf &

# Fix Java apps
wmname LG3D &

# Init polybar
$HOME/.config/polybar/launch.sh

# NewtworkManager-Applet
nm-applet &

# Desktop wallpaper
feh --bg-fill $HOME/Images/Wallpaper/wp_1.png

# Notifications
dunst &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
